### ISSUE TITLE
Some slotProps properties (e.g., inputLabel) are not supported

### ISSUE THREAD

**Issue by metalmarker** [viclafouch/mui-tel-input#171]
MuiTelInput is relying on TextField, which deprecated some props in MUI 6 (e.g., InputProps, inputProps, InputLabelProps, etc) in favor of slotProps. MuiTelInput is [using slotProps internally](https://github.com/viclafouch/mui-tel-input/blob/8de19c99302d43d364c21b187b197668f53f27c0/src/index.tsx#L154), and is including slotProps.htmlInput and slotProps.input, however other slotProps (e.g., inputLabel) will be ignored.

A temporary workaround is use the deprecated props (e.g., InputLabelProps), however support will be removed in MUI 7. 

I propose that MuiTeInput will use  @mui/material/utils/mergeSlotProps internally to merge all provided slotProps properties to resolve this issue and maintain full compatibility with slotProps now and in the future.

**Comment by drod3763** [comment]
Agreed, would like inputProps on the TextField myself.

**Comment by viclafouch** [comment]
Hello ! 

V9 has been released so this issue should be fixed with the upgrade of MUI V7.

See https://github.com/viclafouch/mui-tel-input/releases/tag/v9.0.0

**Comment by metalmarker** [comment]
The problem was not solved - when inputLabel prop (and potentially other props) are passed as part of slotProps, it is ignored. Only htmlInput and input are supported.

**Comment by viclafouch** [comment]
Could you pass an example plz ?

**Comment by metalmarker** [comment]
Providing an example might a bit challenging, but here's information that would help to better communicate the issue. 

The use case is this: I'm using components with variant='outlined' in my app. A normal TextField will show the label of the an unfocused component with no value  inside the textbox, however mui-tel-input always places the label on the border of the component.

Because I still wanted to show the label inside the component (vs. on the border) when it has no value and is unfocused, I've created a wrapped on top of mui-tel-input that is aware to the focus state and "forces" the component to keep the label inside the component by passing this prop:

`
InputLabelProps={{
    shrink: valueExists || focused
}}
`

This way, the inputLabel gets shrink: false when there's no value and no focus.

However, when I'm using slotProps, the following is ignored:

`
      slotProps={{
        inputLabel: {
          shrink: valueExists || focused
        }
      }}
`

Looking at the source code below clearly shows why it doesn't work: the component recomposes slotProps with the external props and its own props, but it does so only for the htmlInput and the input slot properties. It doesn't do it for other slot props. 

Perhaps a potential solution is to add ...slotProps as the first property (before htmlInput), but slotProps can be finicky, so I'm not sure. 

Hopefully, this helped in communicating the issue. Please let me know if additional information is needed. Thanks!

```
slotProps={{
  htmlInput: {
    onCopy: handleCopy,
    ...slotProps?.htmlInput
  },
  input: {
    startAdornment: (
      <InputAdornment position="start" sx={{ flexShrink: 0 }}>
        <FlagButton
          isFlagsMenuOpened={Boolean(anchorEl)}
          isoCode={isoCode}
          forceCallingCode={forceCallingCode}
          onClick={openMenu}
          disabled={disabled}
          getFlagElement={getFlagElement}
          unknownFlagElement={unknownFlagElement}
          disableDropdown={Boolean(disableDropdown)}
          {...FlagIconButtonProps}
        />
      </InputAdornment>
    ),
    ...slotProps?.input
  }
}}```

**Comment by metalmarker** [comment]
Why was this closed? The issue was not fixed yet. This will break once MUI removes support from InputLabelProps.

**Comment by viclafouch** [comment]
"This will break once MUI removes support from InputLabelProps."

 It will be in a major update, so it will be ok, no worries

**Comment by metalmarker** [comment]
Hi @viclafouch, FYI, MUI v9 was just released and has [dropped the support for InputLabelProps](https://next.mui.com/material-ui/migration/upgrade-to-v9/#textfield-props). Is there an ETA for an update? 
Love your package, btw!

**Comment by viclafouch** [comment]
Will push a beta this week, you will be able to use it!

**Comment by metalmarker** [comment]
Thank you @viclafouch for the last release. It looks like this bug was not fixed. As a reminder, my intention is to have a regular (non-shrunk) label when the component (variant=outlined) has no value and is not focused. This is the default behavior of MUI TextField. Since this state does not inherited from TextField, I've used `slotProps={{ inputLabel: { shrink: valueExists || focused } }}` to dynamically control the label state, but it doesn't work.
